project_name: "角色语音识别"
train:
  validate_step: 5
  num_steps: 100
  batch_size: 16
  learning_rate: 1e-6
  device: "cpu"
  num_classes: 60
  sr: 44100
  max_shift: 1000
  noise_factor: 0.05
  train_countinue: False
  log_interval: 5
