project_name: "\u5168\u89D2\u8272"
train:
  batch_size: 16
  device: cpu
  learning_rate: 1e-6
  log_interval: 5
  max_shift: 1000
  noise_factor: 0.05
  num_classes: 60
  num_steps: 100
  sr: 44100
  train_countinue: false
  validate_step: 5
