{
  "project_name": "角色的分类",
  "train": {
    "batch_size": 16,
    "device": "cpu",
    "learning_rate": "1e-6",
    "log_interval": 100,
    "max_shift": 1000,
    "noise_factor": 0.05,
    "num_classes": 60,
    "num_steps": 1000,
    "sr": 44100,
    "train_countinue": false,
    "validate_step": 10
  }
}